project_name : "Food_101"
scheduler : ReduceLROnPlateau(optimizer, 'min')
lr : 0.001
factor : 0.001
optimizer :
          _target_ : torch.optim.Adam
criterion :
          _target_ : torch.nn.CrossEntropyLoss


num_epochs : 1
max_train_hours : 24

num_workers : 1
batch_size : 64
pin_memory : False

patience : 1000
delta : 0.0001
weight_decay : 0.0001
amsgrad : False

