scheduler : ReduceLROnPlateau(optimizer, 'min')
lr : 0.001
factor : 0.001
optimizer :
          _target_ : torch.optim.Adam
criterion :
          _target_ : torch.nn.CrossEntropyLoss

transform_Compose : [
            lambda x: x.float() / 255,
            transforms.RandomResizedCrop(224),
            transforms.RandomHorizontalFlip(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
            transforms.RandAugment(2, 5)
        ]
num_epochs : 1000
max_train_hours : 24

num_workers : 0
batch_size : 64
pin_memory : False

patience : 1000
delta : 0.0001
weight_decay : 0.0001
amsgrad : False

